/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.duan.model.BeanMenu;
import com.duan.DAO.MultiTabControl;
import com.duan.helper.Auth;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static ultility.contraints.*;

/**
 *
 * @author Admin
 */
public class MainGUI extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form StudentDetailsGUI
     */
    int roleData;
    String nameData;
    public MainGUI(String nameData,int roleData) {
        initComponents();
        
        this.nameData=nameData;
        this.roleData=roleData;
        startGUI();
    }

    MainGUI() {
        initComponents();
        ChaoJdialogg dialog = new ChaoJdialogg(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        SignupJDialog dialog1 = new SignupJDialog(new javax.swing.JFrame(), true);
        dialog1.setVisible(true);
        jlbHello.setText("HELLO "+Auth.user.getHoten());
        this.roleData=0;
        startGUI();
    }
    private void startGUI(){
        Thread t =new Thread(this);
        t.start();
//        this.jlbHello.setText("Hi   "+ Auth.user.getMaNV());
        
        setTitle("Phần mềm quản lý Nhà Trọ");
        setLocationRelativeTo(null);
        //setResizable(false);
        MultiTabControl tabControl =new MultiTabControl(jpnView);
        
        if(roleData==0){
            lblContent.setText("QUẢN LÝ NHÂN VIÊN");
            tabControl.setTab(MENUNHANVIEN,jpnnhanvien, jlbnhanvien);
        }
        List<BeanMenu> listMenu =new ArrayList<BeanMenu>();
        listMenu.add(new BeanMenu(MENUNHANVIEN, jpnnhanvien, jlbnhanvien,lblContent,"QUẢN LÝ NHÂN VIÊN"));
        listMenu.add(new BeanMenu(MENUKHACHHANG, jpnkhachhang, jlbkhachhang,lblContent,"QUẢN LÝ KHÁCH HÀNG"));
        listMenu.add(new BeanMenu(MENUHPHONGTRO, jpnphongtro, jlbphongtro,lblContent,"QUẢN LÝ PHÒNG TRỌ"));
        listMenu.add(new BeanMenu(MENUCHIPHI, jpnchiphi, jlbchiphi,lblContent,"QUẢN LÝ CHI PHÍ"));
        listMenu.add(new BeanMenu(MENUHOPDONG, jpnhopdong, jlbhopdong,lblContent,"QUẢN LÝ HỢP ĐỒNG"));
        listMenu.add(new BeanMenu(MENUTHANHTOAN, jpnthanhtoan, jlbthanhtoan,lblContent,"QUẢN LÝ THANH TOÁN"));
        listMenu.add(new BeanMenu(EXIT, jpnExit, jlbExit));
        
        tabControl.setEvent(listMenu);
    }
    @Override
    public void run() {
        while (true) {            
            try {
                runClock();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                break;
            }
        }
    }
    public void runClock(){
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("hh:mm:ss aa");
        String time = sdf.format(now);
        lblClock.setText(time);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnUserInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbHello = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCgangePass = new javax.swing.JButton();
        jlbStudentMarks1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnExit = new javax.swing.JPanel();
        jlbExit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpnthanhtoan = new javax.swing.JPanel();
        jlbthanhtoan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpnphongtro = new javax.swing.JPanel();
        jlbphongtro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpnchiphi = new javax.swing.JPanel();
        jlbchiphi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpnhopdong = new javax.swing.JPanel();
        jlbhopdong = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jpnkhachhang = new javax.swing.JPanel();
        jlbkhachhang = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpnnhanvien = new javax.swing.JPanel();
        jlbnhanvien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        lblContent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnRoot.setBackground(new java.awt.Color(255, 204, 255));

        jpnMenu.setBackground(new java.awt.Color(255, 204, 102));

        jpnUserInfo.setBackground(new java.awt.Color(41, 183, 230));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/user.png"))); // NOI18N

        jlbHello.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbHello.setForeground(new java.awt.Color(255, 255, 255));
        jlbHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHello.setText("Hi Admin");

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/dang xuat bt 35x35_v2.png"))); // NOI18N
        btnLogout.setToolTipText("Đăng xuất");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCgangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/key35x35.png"))); // NOI18N
        btnCgangePass.setToolTipText("Đổi password");
        btnCgangePass.setBorderPainted(false);
        btnCgangePass.setContentAreaFilled(false);
        btnCgangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCgangePass.setFocusable(false);
        btnCgangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCgangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnUserInfoLayout = new javax.swing.GroupLayout(jpnUserInfo);
        jpnUserInfo.setLayout(jpnUserInfoLayout);
        jpnUserInfoLayout.setHorizontalGroup(
            jpnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCgangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnUserInfoLayout.setVerticalGroup(
            jpnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCgangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jlbStudentMarks1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbStudentMarks1.setForeground(new java.awt.Color(0, 51, 204));
        jlbStudentMarks1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbStudentMarks1.setText("Kisami APP");

        jPanel1.setBackground(new java.awt.Color(41, 183, 230));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jpnExit.setBackground(new java.awt.Color(41, 183, 230));

        jlbExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbExit.setForeground(new java.awt.Color(255, 255, 255));
        jlbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbExit.setText("THOÁT");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/thiet bi bd 30x51.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnExitLayout = new javax.swing.GroupLayout(jpnExit);
        jpnExit.setLayout(jpnExitLayout);
        jpnExitLayout.setHorizontalGroup(
            jpnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(jlbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jpnExitLayout.setVerticalGroup(
            jpnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jlbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpnthanhtoan.setBackground(new java.awt.Color(41, 183, 230));

        jlbthanhtoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbthanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        jlbthanhtoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbthanhtoan.setText("QUẢN LÍ THANH TOÁN");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/phieu nhap bd 30x51.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnthanhtoanLayout = new javax.swing.GroupLayout(jpnthanhtoan);
        jpnthanhtoan.setLayout(jpnthanhtoanLayout);
        jpnthanhtoanLayout.setHorizontalGroup(
            jpnthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthanhtoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnthanhtoanLayout.setVerticalGroup(
            jpnthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthanhtoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)))
        );

        jpnphongtro.setBackground(new java.awt.Color(41, 183, 230));

        jlbphongtro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbphongtro.setForeground(new java.awt.Color(255, 255, 255));
        jlbphongtro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbphongtro.setText("QUẢN LÍ PHÒNG TRỌ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/nhan vien bd 30x51.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnphongtroLayout = new javax.swing.GroupLayout(jpnphongtro);
        jpnphongtro.setLayout(jpnphongtroLayout);
        jpnphongtroLayout.setHorizontalGroup(
            jpnphongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnphongtroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jlbphongtro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(17, 17, 17))
        );
        jpnphongtroLayout.setVerticalGroup(
            jpnphongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnphongtroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnphongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jlbphongtro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jpnchiphi.setBackground(new java.awt.Color(41, 183, 230));

        jlbchiphi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbchiphi.setForeground(new java.awt.Color(255, 255, 255));
        jlbchiphi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbchiphi.setText("QUẢN LÍ CHI PHÍ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/nhan vien bd 30x51.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnchiphiLayout = new javax.swing.GroupLayout(jpnchiphi);
        jpnchiphi.setLayout(jpnchiphiLayout);
        jpnchiphiLayout.setHorizontalGroup(
            jpnchiphiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnchiphiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jlbchiphi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(17, 17, 17))
        );
        jpnchiphiLayout.setVerticalGroup(
            jpnchiphiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnchiphiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnchiphiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jlbchiphi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        jpnhopdong.setBackground(new java.awt.Color(41, 183, 230));

        jlbhopdong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbhopdong.setForeground(new java.awt.Color(255, 255, 255));
        jlbhopdong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbhopdong.setText("QUẢN LÍ HỢP ĐỒNG");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/nhan vien bd 30x51.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnhopdongLayout = new javax.swing.GroupLayout(jpnhopdong);
        jpnhopdong.setLayout(jpnhopdongLayout);
        jpnhopdongLayout.setHorizontalGroup(
            jpnhopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnhopdongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addComponent(jlbhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(17, 17, 17))
        );
        jpnhopdongLayout.setVerticalGroup(
            jpnhopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhopdongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnhopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jlbhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnkhachhang.setBackground(new java.awt.Color(41, 183, 230));

        jlbkhachhang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbkhachhang.setForeground(new java.awt.Color(255, 255, 255));
        jlbkhachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbkhachhang.setText("QUẢN LÍ KHÁCH HÀNG");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/nhan vien bd 30x51.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnkhachhangLayout = new javax.swing.GroupLayout(jpnkhachhang);
        jpnkhachhang.setLayout(jpnkhachhangLayout);
        jpnkhachhangLayout.setHorizontalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnkhachhangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(12, 12, 12)
                .addComponent(jlbkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(17, 17, 17))
        );
        jpnkhachhangLayout.setVerticalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhachhangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jlbkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)))
        );

        jpnnhanvien.setBackground(new java.awt.Color(41, 183, 230));

        jlbnhanvien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbnhanvien.setForeground(new java.awt.Color(255, 255, 255));
        jlbnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbnhanvien.setText("QUẢN LÍ NHÂN VIÊN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/tai khoan bd 30x51.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/border right 30x51.png"))); // NOI18N

        javax.swing.GroupLayout jpnnhanvienLayout = new javax.swing.GroupLayout(jpnnhanvien);
        jpnnhanvien.setLayout(jpnnhanvienLayout);
        jpnnhanvienLayout.setHorizontalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnnhanvienLayout.setVerticalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnnhanvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnnhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnphongtro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jpnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpnthanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnchiphi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpnhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnphongtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnchiphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jpnhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudentMarks1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jpnUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbStudentMarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));

        lblClock.setBackground(new java.awt.Color(41, 183, 230));
        lblClock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(41, 183, 230));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/clock.png"))); // NOI18N
        lblClock.setText("00:00:00 PM");

        jpnView.setPreferredSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblContent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblContent.setForeground(new java.awt.Color(41, 183, 230));
        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContent.setText("lblContent");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblClock)
                .addContainerGap())
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCgangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCgangePassActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btnCgangePassActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
        } catch (InstantiationException ex) {
            
        } catch (IllegalAccessException ex) {
           
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCgangePass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlbExit;
    private javax.swing.JLabel jlbHello;
    private javax.swing.JLabel jlbStudentMarks1;
    private javax.swing.JLabel jlbchiphi;
    private javax.swing.JLabel jlbhopdong;
    private javax.swing.JLabel jlbkhachhang;
    private javax.swing.JLabel jlbnhanvien;
    private javax.swing.JLabel jlbphongtro;
    private javax.swing.JLabel jlbthanhtoan;
    private javax.swing.JPanel jpnExit;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnUserInfo;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnchiphi;
    private javax.swing.JPanel jpnhopdong;
    private javax.swing.JPanel jpnkhachhang;
    private javax.swing.JPanel jpnnhanvien;
    private javax.swing.JPanel jpnphongtro;
    private javax.swing.JPanel jpnthanhtoan;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblContent;
    // End of variables declaration//GEN-END:variables
}
