/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import co.yogesh.Captcha;
import com.duan.DAO.nhanVienDAO;
import com.duan.helper.Auth;
import com.duan.helper.MgsBoxhelper;
import com.duan.model.Nhanvien;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author THANH
 */
public class SignupJDialog extends javax.swing.JDialog {

    /**
     * Creates new form SignupJDialog
     */
    Captcha cap = new Captcha();
    Frame parent;

    public SignupJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        init();
        cap.setImageCaptcha(captcha);
    }

    void init() {
        setLocationRelativeTo(null);

    }

    void dangnhap() {
        try {
            nhanVienDAO dao = new nhanVienDAO();
            String manv = txtMaNV.getText();
            String matKhau = new String(txtMatKhau.getPassword());
            Nhanvien nhanvien = dao.selectById(manv);
            if (nhanvien == null) {
                MgsBoxhelper.alert(this, "sai tên đăng nhập");

            } else if (!matKhau.equals(nhanvien.getPassword())) {
                MgsBoxhelper.alert(this, "sai mật khẩu!");

            } else {
                Auth.user = nhanvien;
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void ketthuc() {
        if (MgsBoxhelper.confirm(this, "bạn có muốn kết thúc không?")) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btn_signup1 = new javax.swing.JButton();
        txtnhapcapt = new javax.swing.JTextField();
        captcha = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_signup2 = new javax.swing.JButton();
        ckShow = new javax.swing.JCheckBox();
        textForm1 = new javax.swing.JLabel();
        textForm2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaNV.setText("NV01");
        txtMaNV.setBorder(null);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        jPanel2.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 150, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, 10));

        txtMatKhau.setText("vuong");
        txtMatKhau.setBorder(null);
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        jPanel2.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/21-avatar-outline (1).gif"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btn_signup1.setBackground(new java.awt.Color(0, 204, 204));
        btn_signup1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_signup1.setText("Login with QRcode");
        btn_signup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 40));

        txtnhapcapt.setBorder(null);
        txtnhapcapt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhapcaptActionPerformed(evt);
            }
        });
        jPanel2.add(txtnhapcapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 150, 30));
        jPanel2.add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 160, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 370, 10));

        btn_signup2.setBackground(new java.awt.Color(0, 204, 204));
        btn_signup2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_signup2.setText("Sign up");
        btn_signup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 290, 40));

        ckShow.setBackground(new java.awt.Color(255, 255, 255));
        ckShow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckShow.setForeground(new java.awt.Color(57, 113, 177));
        ckShow.setText("Show password");
        ckShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckShowMouseClicked(evt);
            }
        });
        ckShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckShowActionPerformed(evt);
            }
        });
        jPanel2.add(ckShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        textForm1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textForm1.setForeground(new java.awt.Color(0, 204, 204));
        textForm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/user1.png"))); // NOI18N
        textForm1.setText("USERNAME");
        jPanel2.add(textForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        textForm2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textForm2.setForeground(new java.awt.Color(0, 204, 204));
        textForm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/key.png"))); // NOI18N
        textForm2.setText("PASSWORD");
        jPanel2.add(textForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 500, 530));

        jPanel5.setBackground(new Color(0,0,0,200
        )
    );

    jLabel5.setFont(new java.awt.Font("UTM Americana", 0, 36)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 204, 204));
    jLabel5.setText("Kasami App");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(369, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addGap(127, 127, 127))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(221, 221, 221)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(248, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 530));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/person-writing-on-white-paper-3803252.jpg"))); // NOI18N

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 530));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtnhapcaptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhapcaptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhapcaptActionPerformed

    private void btn_signup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup1ActionPerformed
        // TODO add your handling code here:
        new Cam(parent, true).setVisible(true);
        if (Auth.user != null) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_signup1ActionPerformed

    private void btn_signup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup2ActionPerformed
        // TODO add your handling code here:
        if (cap.Validate(captcha, txtnhapcapt.getText())) {
            JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công");
            this.dangnhap();
        } else {
            JOptionPane.showMessageDialog(this, "nhập captcha sai");
        }
    }//GEN-LAST:event_btn_signup2ActionPerformed

    private void ckShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckShowActionPerformed

    private void ckShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckShowMouseClicked
        // TODO add your handling code here:
        if (ckShow.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_ckShowMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignupJDialog dialog = new SignupJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup1;
    private javax.swing.JButton btn_signup2;
    private javax.swing.JLabel captcha;
    private javax.swing.JCheckBox ckShow;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel textForm1;
    private javax.swing.JLabel textForm2;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtnhapcapt;
    // End of variables declaration//GEN-END:variables
}
